### ISSUE TITLE
Brainstorming: CodeSpaces Instructions

### ISSUE THREAD

**Issue by hamelsmu** [jupyterhub/repo2docker-action#39]
[CodeSpaces](https://github.com/features/codespaces/) is currently in Beta.  However, it will be released soon (I don't know exactly when).  Repo2Docker and this Action will be extremely useful for that to facilitate the launching of Jupyter Notebooks in that environment.  

**Note: Codespaces allows you to launch arbitrary apps like Jupyter Notebooks on a different port and connect to that port**

It will look something like this https://www.youtube.com/watch?v=Hpt1Xs96C74&feature=youtu.be

P.S. the CodeSpaces config looks like this https://github.com/jupyterhub/repo2docker-action/blob/master/.devcontainer/devcontainer.json

cc: @betatim @choldgraf

**Comment by choldgraf** [comment]
thanks for putting this on the radar - how does codespaces differ from something like Binder? Does it only allow for vscode, or other interfaces as well?

**Comment by hamelsmu** [comment]
Good question Codespaces allows for any arbitrary web application to run on any port in addition to VSCode.  My preferred way of using it for example will be serve Jupyter Lab on it 🎉 

I think Binder has more generous compute at the moment than the free version of CodeSpaces but that might change

**Comment by choldgraf** [comment]
A general thought here - I think that we should find ways to show how repo2docker can plug in to other ecosystems, be used in workflows out of Binder etc. To that extent I think it'd be great to see information about how to integrate with codespaces!

That said, I think we should also show some caution, because codespaces falls more into the category of "vendor products" and we generally don't want to show preference for one vs the other (e.g. codespaces / gitpod / colab / cocalc / codeocean / etc). That said, it's pretty neat that codespaces works with open standards like repo2docker, so it's definitely worth highlighting and recognizing - I'm not quite sure how to walk that line! 🤔🤔🤔

**Comment by hamelsmu** [comment]
That's an interesting point!   I was also contemplating using repo2docker to launch notebook VMs on the cloud of your choice, which can be useful for compute like GPUs or other heavy workloads where mybinder.org may not be appropriate?  The challenge is that infrastructure isn't free so it also starts to skate in this vendor zone of integrating with the cloud providers (AWS, GCP, Azure).  

That being said, I think as practical matter folks may find it interesting for example, [some interest](https://twitter.com/hugobowne/status/1286226547242754048?s=20) from @hugobowne to use while doing Dask training at conferences.  

I [opened a thread on discourse to solicit more thoughts and opinions](https://discourse.jupyter.org/t/brainstorming-repo2docker-action-vm-on-gcp-aws-azure/5345)

**Comment by choldgraf** [comment]
oh I think the general use-case of "repo2docker connected with XXX" is an awesome one to highlight. And agreed re: quickly spin up a docker container in the cloud that is powered by an environment you create with repo2docker, that'd be really cool (we've also nibbled around a similar idea that uses `the littlest jupyterhub` so you can create a quick hub w/ an environment that was defined with repo2docker files)

**Comment by hamelsmu** [comment]
I'll close this issue thanks it was helpful to gather ideas etc from this
