### ISSUE TITLE
Docker error message

### ISSUE THREAD

**Issue by bluescarni** [jupyterhub/repo2docker-action#74]
**Describe the bug**
Since a few days, this github action is not working properly for me any more. For reference, I am using the most basic setup as described in the project README - here's my yml file:

https://github.com/bluescarni/heyoka.py/blob/main/.github/workflows/gh_actions_ci.yml#L46

When the action executes after a push to ``main``, it fails with error message:

```console
 IMAGE_NAME must be explicitly set when DOCKER_USERNAME isn't set.
```

See here for the complete logs:

https://github.com/bluescarni/heyoka.py/runs/3074724754

I did not change anything in my CI configuration files recently.

**Expected behavior**
The action should execute correctly.

**Comment by yuvipanda** [comment]
Thank you for reporting this, @bluescarni

@consideRatio do you think this is related to #73?

**Comment by yuvipanda** [comment]
ok I think https://github.com/jupyterhub/repo2docker-action/pull/73/files#r670389529 is the cause

**Comment by consideRatio** [comment]
This was intentional from #73 (https://github.com/jupyterhub/repo2docker-action/pull/73#discussion_r665752417). I didn't see this to be documented behavior in any place so it felt reasonable to not set DOCKER_USERNAME to be $GITHUB_ACTOR and then let IMAGE_NAME be set with DOCKER_USERNAME as a fallback.

I don't consider this a bug but rather intentional behavior given the documentation we have. No examples in the docs are broken still right? What is the intentional behavior that is wanted though?

**Comment by yuvipanda** [comment]
> What is desired, to have the example in the readme updated, or the logic updated to be like before and with all that logic which was quite non-obvious described?

I think we should update the logic, since in many NO_PUSH situations you don't care about the image name.

**Comment by bluescarni** [comment]
Thanks! I can confirm the action is again working properly on my side.
